import type { AgentConfig, MeetingEvent } from "./types";

export const agents: AgentConfig[] = [
  {
    id: "host",
    name: "主持人",
    emoji: "🎩",
    role: "控场总结",
    position: "bottom",
    color: "from-violet-200 to-purple-100",
  },
  {
    id: "product",
    name: "产品专家",
    emoji: "🧭",
    role: "MVP 边界",
    position: "top",
    color: "from-sky-200 to-blue-100",
  },
  {
    id: "tech",
    name: "技术专家",
    emoji: "🛠️",
    role: "工程取舍",
    position: "right",
    color: "from-emerald-200 to-teal-100",
  },
  {
    id: "growth",
    name: "增长专家",
    emoji: "📈",
    role: "需求验证",
    position: "left",
    color: "from-orange-200 to-amber-100",
  },
];

export const mockEvents: MeetingEvent[] = [
  {
    id: "evt_001",
    type: "speech",
    speakerId: "host",
    emotion: "thinking",
    action: "open",
    text: "今天只讨论一件事：两周内这个 MVP 到底该砍到多小。",
    delay_before_ms: 300,
    duration_ms: 2600,
  },
  {
    id: "evt_002",
    type: "speech",
    speakerId: "product",
    emotion: "excited",
    action: "suggest",
    text: "我先反对做完整报表。老板要的不是图表，而是现金流什么时候会断。",
    delay_before_ms: 400,
    duration_ms: 3200,
  },
  {
    id: "evt_003",
    type: "speech",
    speakerId: "tech",
    targetId: "product",
    emotion: "worried",
    action: "challenge",
    text: "方向可以，但我反对第一版接银行接口。两周内风险太高，只能先做 CSV 上传。",
    delay_before_ms: 500,
    duration_ms: 3400,
  },
  {
    id: "evt_004",
    type: "speech",
    speakerId: "growth",
    targetId: "product",
    emotion: "angry",
    action: "reject",
    text: "你们又急着做产品了。先拿假原型找 5 个老板验证，没人催款就别写代码。",
    delay_before_ms: 500,
    duration_ms: 3400,
  },
  {
    id: "evt_005",
    type: "speech",
    speakerId: "host",
    emotion: "happy",
    action: "summarize",
    text: "好，分歧已经清楚了：不是做不做 AI，而是先验证老板会不会因此行动。",
    delay_before_ms: 500,
    duration_ms: 3000,
  },
  {
    id: "evt_006",
    type: "summary",
    delay_before_ms: 300,
    duration_ms: 999999,
    summary: {
      direction: "先做现金流预警，不做完整财务报表。",
      disagreement: "是否接银行接口。技术侧建议第一版只支持 CSV 上传。",
      nextStep: "用 3 到 5 个真实老板测试预警短信是否促成催款行动。",
    },
  },
];
