import type { MeetingEvent } from "./types";

/**
 * 压力测试用 mock 剧本（默认播放仍使用 mockEvents.ts）。
 * 结构与时序与主 mock 一致，仅替换发言/小结文案风格。
 */
export const mockScenarios = {
  concise: {
    label: "精炼版",
    events: [
      {
        id: "evt_001",
        type: "speech",
        speakerId: "host",
        emotion: "thinking",
        action: "open",
        text: "两周 MVP 范围，今天定稿。",
        delay_before_ms: 300,
        duration_ms: 2600,
      },
      {
        id: "evt_002",
        type: "speech",
        speakerId: "product",
        emotion: "excited",
        action: "suggest",
        text: "只做现金流预警，不做报表。",
        delay_before_ms: 400,
        duration_ms: 3200,
      },
      {
        id: "evt_003",
        type: "speech",
        speakerId: "tech",
        targetId: "product",
        emotion: "worried",
        action: "challenge",
        text: "不接银行，先 CSV。",
        delay_before_ms: 500,
        duration_ms: 3400,
      },
      {
        id: "evt_004",
        type: "speech",
        speakerId: "growth",
        targetId: "product",
        emotion: "angry",
        action: "reject",
        text: "先验证 5 个老板，再写代码。",
        delay_before_ms: 500,
        duration_ms: 3400,
      },
      {
        id: "evt_005",
        type: "speech",
        speakerId: "host",
        emotion: "happy",
        action: "summarize",
        text: "共识：先验证行动，不堆功能。",
        delay_before_ms: 500,
        duration_ms: 3000,
      },
      {
        id: "evt_006",
        type: "summary",
        delay_before_ms: 300,
        duration_ms: 999999,
        summary: {
          direction: "现金流预警优先。",
          disagreement: "是否接银行。",
          nextStep: "5 家老板验证催款动作。",
        },
      },
    ] satisfies MeetingEvent[],
  },
  verbose: {
    label: "啰嗦版",
    events: [
      {
        id: "evt_001",
        type: "speech",
        speakerId: "host",
        emotion: "thinking",
        action: "open",
        text: "各位，我们今天花整整一轮时间，只讨论一件事：在两周这个非常紧的窗口里，这个面向中小企业老板的 AI 财务助手，MVP 到底应该砍到什么程度，哪些必须留、哪些必须砍。",
        delay_before_ms: 300,
        duration_ms: 2600,
      },
      {
        id: "evt_002",
        type: "speech",
        speakerId: "product",
        emotion: "excited",
        action: "suggest",
        text: "我强烈建议不要一上来就做完整报表和可视化大屏。老板真正焦虑的是：按照现在的回款和支出节奏，现金流大概什么时候会见底，而不是再看一张漂亮但滞后的利润表。",
        delay_before_ms: 400,
        duration_ms: 3200,
      },
      {
        id: "evt_003",
        type: "speech",
        speakerId: "tech",
        targetId: "product",
        emotion: "worried",
        action: "challenge",
        text: "方向我基本同意，但我必须质疑第一版就去接银行开放接口这件事：合规、联调、异常对账都会把两周拖成两个月。更现实的路径是 CSV 上传加规则引擎，先跑通端到端。",
        delay_before_ms: 500,
        duration_ms: 3400,
      },
      {
        id: "evt_004",
        type: "speech",
        speakerId: "growth",
        targetId: "product",
        emotion: "angry",
        action: "reject",
        text: "你们又开始堆产品了。我的反对意见很简单：在没有任何真实老板愿意为「预警」付钱之前，写再多代码都是自嗨。请先拿假原型找五家目标用户，看会不会真的去催款。",
        delay_before_ms: 500,
        duration_ms: 3400,
      },
      {
        id: "evt_005",
        type: "speech",
        speakerId: "host",
        emotion: "happy",
        action: "summarize",
        text: "好，我把分歧收束一下：不是争论要不要 AI，而是先验证老板会不会因为预警而采取催款行动；技术路径可以先用 CSV，银行接口放到明确验证之后。",
        delay_before_ms: 500,
        duration_ms: 3000,
      },
      {
        id: "evt_006",
        type: "summary",
        delay_before_ms: 300,
        duration_ms: 999999,
        summary: {
          direction:
            "两周 MVP 聚焦现金流预警与见底倒计时，不做完整财务报表体系。",
          disagreement:
            "银行接口是否纳入第一版：产品倾向尽快验证价值，技术强调两周内只能 CSV。",
          nextStep:
            "用 3～5 位真实中小企业老板做原型测试，观察预警是否触发实际催款行为。",
        },
      },
    ] satisfies MeetingEvent[],
  },
  weak: {
    label: "弱质量/跑题版",
    events: [
      {
        id: "evt_001",
        type: "speech",
        speakerId: "host",
        emotion: "thinking",
        action: "open",
        text: "那个……我们就随便聊聊吧，两周好像也挺长的，要不先看看竞品怎么做的？",
        delay_before_ms: 300,
        duration_ms: 2600,
      },
      {
        id: "evt_002",
        type: "speech",
        speakerId: "product",
        emotion: "excited",
        action: "suggest",
        text: "我觉得可以加很多图表，再顺便做个老板社区，用户粘性会更高，财务只是入口。",
        delay_before_ms: 400,
        duration_ms: 3200,
      },
      {
        id: "evt_003",
        type: "speech",
        speakerId: "tech",
        targetId: "product",
        emotion: "worried",
        action: "challenge",
        text: "社区和图表都偏题了……如果坚持两周交付，我建议先 CSV，别一上来谈银行。",
        delay_before_ms: 500,
        duration_ms: 3400,
      },
      {
        id: "evt_004",
        type: "speech",
        speakerId: "growth",
        targetId: "product",
        emotion: "angry",
        action: "reject",
        text: "你们都在讲功能，没人问老板会不会付钱。先找五个人聊，别写代码。",
        delay_before_ms: 500,
        duration_ms: 3400,
      },
      {
        id: "evt_005",
        type: "speech",
        speakerId: "host",
        emotion: "happy",
        action: "summarize",
        text: "好吧，先回到现金流预警，社区以后再说。",
        delay_before_ms: 500,
        duration_ms: 3000,
      },
      {
        id: "evt_006",
        type: "summary",
        delay_before_ms: 300,
        duration_ms: 999999,
        summary: {
          direction: "（勉强）先讨论现金流预警，但会议前期跑题较多。",
          disagreement: "产品想加社区/图表，增长与技术的焦点不一致。",
          nextStep: "需要重新对齐目标用户与两周 MVP 边界后再排期。",
        },
      },
    ] satisfies MeetingEvent[],
  },
} as const;

export type MockScenarioKey = keyof typeof mockScenarios;
